[workspace]
members = ["core", "server"]
resolver = "3"

[workspace.dependencies]
omnistat-core = { path = "core" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"